cp ./explain.c ../postgres/src/backend/commands/
cp ./Makefile ../postgres/src/backend/executor/
cp ./execAmi.c ../postgres/src/backend/executor/
cp ./execCurrent.c ../postgres/src/backend/executor/
cp ./execProcnode.c ../postgres/src/backend/executor/
cp ./nodeSamplescan.c ../postgres/src/backend/executor/
cp ./copyfuncs.c ../postgres/src/backend/nodes/
cp ./outfuncs.c ../postgres/src/backend/nodes/
cp ./createplan.c ../postgres/src/backend/optimizer/plan/
cp ./setrefs.c ../postgres/src/backend/optimizer/plan/
cp ./subselect.c ../postgres/src/backend/optimizer/plan/
cp ./pathnode.c ../postgres/src/backend/optimizer/util/
cp ./nodeSamplescan.h ../postgres/src/include/executor/
cp ./execnodes.h ../postgres/src/include/nodes/
cp ./nodes.h ../postgres/src/include/nodes/
cp ./plannodes.h ../postgres/src/include/nodes/
cp ./pathnode.h ../postgres/src/include/optimizer/
cp ./cost.h ../postgres/src/include/optimizer/
cp ./costsize.c ../postgres/src/backend/optimizer/path/
cp ./allpaths.c ../postgres/src/backend/optimizer/path/
cp ./gram.y ../postgres/src/backend/parser/
cp ./primnodes.h ../postgres/src/include/nodes/
cp ./kwlist.h ../postgres/src/include/parser/
cp ./parse_clause.c ../postgres/src/backend/parser/
cp ./parsenodes.h ../postgres/src/include/nodes/
cp ./parse_relation.c ../postgres/src/backend/parser/
cp ./ruleutils.c ../postgres/src/backend/utils/adt/
cp ./errcodes.txt ../postgres/src/backend/utils/
cp ./relation.h ../postgres/src/include/nodes/
cp ./relnode.c ../postgres/src/backend/optimizer/util/
cp ./analyze.c ../postgres/src/backend/parser/
cp ./equalfuncs.c ../postgres/src/backend/nodes/
cp ./readfuncs.c ../postgres/src/backend/nodes/
cp ./heapam.c ../postgres/src/backend/access/heap/
cp ./heapam.h ../postgres/src/include/access/
cp ./relscan.h ../postgres/src/include/access/
